### ISSUE TITLE
Setting up server

### ISSUE THREAD

**Issue by diegowrhasta** [Myaamori/progress-bot#1]
Thanks for the pointers made on the reply to the comment made on the last commit, as well as opening up the Issues tab, I've managed to get the bot to reply on the discord server, here's an excerpt of his replies:
```
Added show: my-show - Full Title of Show
Full Title of Show | Episode 01 | Typesetting progress @ 44%
Full Title of Show | Episode 01 | Edit progress @ 0%
Full Title of Show | Episode 01 | Quality Control progress @ 67%
```

```
Added show: show_1 - The Testing Show
The Testing Show | Episode 01 | Translation progress @ 100%
Currently working on The Testing Show episode 02
```

The problem now stands on the front-end side I think, the page is still blank, no updates it seems.

**Comment by Myaamori** [comment]
First make sure that `enableHttp` is set to `true` in config.js. If you're then able to connect to `http://localhost:PORT`, something is going wrong with actually retrieving the show data. If you open developer tools in your browser and go to the network tab, do you see any requests to `http://localhost:PORT/socket.io`? And if so, do they succeed?

Also check if you see any errors in the terminal where the process is running when you attempt to access the server.

**Comment by Myaamori** [comment]
Ah yes, I just realized: The index.html is not really a working status page as such, but more of an example on how to include the status script. You'll have to manually edit the `data-port` attribute and the address of the web server, if you're using something other than localhost and port 8088.

**Comment by diegowrhasta** [comment]
Hey, yep spot on with the last one. Finally got the data to show on the webpage and update with commands. Thanks a lot.

**Comment by Myaamori** [comment]
Awesome, great to hear it worked. If you have any suggestions for additional features that you think would be useful, let me know. While there's no up-to-date documentation on the available features, you can have a look at this file to see what commands are currently defined: https://github.com/Myaamori/progress-bot/blob/master/common.js#L270
